method: bayes
early_terminate: 
  type: hyperband
  min_iter: 7  
  max_iter: 20
  eta: 2
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs:
    values: [10]
  batch_size:
    values: [32, 64]
  num_filters:
    values: 
      - [32, 32, 32, 32, 32]
      - [64, 64, 64, 64, 64]
      - [32, 64, 128, 256, 512]
  kernel_size:
    values: [3, 5]
  activation:
    values: ["relu", "gelu"]
  dense_neurons:
    values: [128, 256]
  dropout_rate:
    values: [0.0, 0.2]
  lr:
    values: [0.001, 0.0001]
  weight_decay:
    values: [0.0, 0.001]
  optimizer:
    values: ["adam", "sgd"]
  use_aug:
    values: [true, false]
  use_batchnorm:
    values: [true, false]
